### ISSUE TITLE
can't login have only message invalid login?

### ISSUE THREAD

**Issue by vixivixi** [rudiedirkx/Jira#33]
if i make debug i have no issue 
where i need to search the truble!
Jira 6.2.2
Thanks. 
it great idea to make jira more frendly. for mobile!

**Comment by rudiedirkx** [comment]
* Make sure the username and password don't have spaces. I don't think it matters, but it might.
* The URL might be wrong. If the website dashboard is at "https://yourbiz.jira.com/secure/Dashboard.jspa", you should use "https://yourbiz.jira.com" as URL. No trailing `/` necessary, and don't include `/rest` in the URL.

It that doesn't do it, add this after `$account = ....`:

````
var_dump($account);
var_dump($error);
var_dump($info);
````

`$error` is a number if something's wrong. `$info` should contain all the cURL info. Anything useful in there?

**Comment by vixivixi** [comment]
1.no space in username & password
2. domain is local on https://srv - but the log is silent
3. error is 0

bool(false)
int(0)
array(29) {
  ["url"]=>
  string(35) "/rest/api/2/user?username=v.lizneva"
  ["content_type"]=>
  NULL
  ["http_code"]=>
  int(0)
  ["header_size"]=>
  int(0)
  ["request_size"]=>
  int(0)
  ["filetime"]=>
  int(-1)
  ["ssl_verify_result"]=>
  int(0)
  ["redirect_count"]=>
  int(0)
  ["total_time"]=>
  float(0)
  ["namelookup_time"]=>
  float(0)
  ["connect_time"]=>
  float(0)
  ["pretransfer_time"]=>
  float(0)
  ["size_upload"]=>
  float(0)
  ["size_download"]=>
  float(0)
  ["speed_download"]=>
  float(0)
  ["speed_upload"]=>
  float(0)
  ["download_content_length"]=>
  float(-1)
  ["upload_content_length"]=>
  float(-1)
  ["starttransfer_time"]=>
  float(0)
  ["redirect_time"]=>
  float(0)
  ["certinfo"]=>
  array(0) {
  }
  ["primary_ip"]=>
  string(0) ""
  ["primary_port"]=>
  int(0)
  ["local_ip"]=>
  string(0) ""
  ["local_port"]=>
  int(0)
  ["redirect_url"]=>
  string(0) ""
  ["headers"]=>
  array(0) {
  }
  ["response"]=>
  NULL
  ["error"]=>
  string(0) ""
}

**Comment by rudiedirkx** [comment]
It looks like the call to Jira failed completely. The server wasn't even reached. Maybe `https://srv` is local/lan or behind a lan firewall? Your browser directly will understand, so accessing the URL directly works, but the webserver doesn't seem to understand.

Bootstrap is horrible and huge. I don't believe in ready-all-in-1 solutions.

**Comment by vixivixi** [comment]
thanks man.
for now i use "chobie/jira-api-restclient" - this solution is working, sad but i can't use yours 
but maybe something gona happens!! & i can start it.
& try to connect it to Bootstrap - it look nice for now.

PS: maybe it links with ssl & sertification mode.
thanks!

**Comment by rudiedirkx** [comment]
That class works, because it has

```
curl_setopt($curl, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($curl, CURLOPT_SSL_VERIFYHOST, 0);
```

which practically means, ignore all https, just accept anything. If you don't want to use https, enter the http URL without s. If the server doesn't accept that, it's with good reason.
